name: Python CI

on:
  push:
    branches:
      - feat/ETL-first-push # Adjust branch name as needed
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11  # Choose the Python version you want to use
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Adjust if you have requirements file
    
    - name: Run tests
      run: |
        pytest test_etl_processor.py --cov=test_etl_processor --cov-report=xml:coverage/test_etl_processor/coverage.xml
        pytest test_db_handler.py --cov=test_db_handler --cov-report=xml:coverage/test_db_handler/coverage.xml

    
    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage/**/coverage.xml
        badge: true
        fail_below_min: true
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: both
        thresholds: '95'

    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        number: 5
        recreate: true
        path: code-coverage-results.md